package com.example.dle_prototype.data.qa

/**
 * Message entry in the Q&A study chat session.
 */
data class QaChatMessage(
    val id: Long = 0,
    val username: String,
    val sender: String, // "user" or "assistant"
    val message: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Curated knowledge base entry for grounding Q&A study assistance.
 */
data class QaKnowledgeEntry(
    val id: String,
    val category: String,
    val title: String,
    val keywords: List<String>,
    val explanation: String,
    val codeSnippet: String? = null,
    val relatedFollowUps: List<String> = emptyList()
)

/**
 * Response generated by the Q&A engine.
 */
data class QaResponse(
    val answer: String,
    val category: String,
    val confidence: Float,
    val codeSnippet: String? = null,
    val suggestedFollowUps: List<String> = emptyList()
)
